# Generated by Django 5.2.4 on 2025-07-08 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulta",
            name="id",
        ),
        migrations.RemoveField(
            model_name="paciente",
            name="id",
        ),
        migrations.AddField(
            model_name="consulta",
            name="consulta_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="paciente",
            name="paciente_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="paciente",
            field=models.ForeignKey(
                db_column="paciente_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="pacientes.paciente",
            ),
        ),
        migrations.AlterModelTable(
            name="consulta",
            table="consultas",
        ),
        migrations.AlterModelTable(
            name="paciente",
            table="pacientes",
        ),
    ]
