# Generated by Django 5.2.4 on 2025-07-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_consulta_id_remove_paciente_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPlanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('relato_consulta', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datos_planos',
            },
        ),
    ]
