# Generated by Django 5.2.4 on 2025-10-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_datosplanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('medicacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
                ('esquema', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'medicaciones',
            },
        ),
        migrations.DeleteModel(
            name='DatosPlanos',
        ),
        migrations.AddField(
            model_name='consulta',
            name='riesgo',
            field=models.IntegerField(choices=[(0, 'POS (bajo)'), (1, 'NEU (medio)'), (2, 'NEG (alto)')], default=1),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='consulta',
            field=models.ForeignKey(db_column='consulta_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='pacientes.consulta'),
        ),
    ]
